START TRANSACTION; # 트랜잭션 시작
# BEGIN / BEGIN WORK도 위 트랜잭션과 같은 기능

USE SHOPPINGMALL;

# PR_CODE가 FOO002 가격을 2000원으로 수정
UPDATE PRODUCT SET PR_PRICE = 2000 WHERE PR_CODE = 'FOO002';

SAVEPOINT A;

UPDATE PRODUCT SET PR_PRICE = 1000 WHERE PR_CODE = 'FOO002';

ROLLBACK;		# TRANSACTION 시작 전으로 되돌리기
ROLLBACK TO A;	# SAVEPOINT A가 있는 위치로 되돌리기

COMMIT;	# 변경 사항을 최종 적용
SELECT * FROM PRODUCT;